version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - sf_network
    volumes:
      - "./data/elasticsearch:/usr/share/elasticsearch/data:delegated"
    environment:
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "8004:9200"
    labels:
      traefik.frontend.rule: "Host:es.shopping-feed.lan"
      traefik.backend: "elasticsearch"
      traefik.port: "9200"
      traefik.docker.network: "sf_network"
      traefik.enable: "true"

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    networks:
      - sf_network
    volumes:
      - "./data/rabbitmq:/var/lib/rabbitmq:delegated"
    expose:
      - 5672
    ports:
      - "8001:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    labels:
      traefik.frontend.rule: "Host:rbmq.shopping-feed.lan"
      traefik.backend: "rabbitmq"
      traefik.port: "15672"
      traefik.docker.network: "sf_network"
      traefik.enable: "true"

  redis:
    image: redis:4.0-alpine
    ports:
      - "8002:6379"
    expose:
      - 6379
    networks:
      - sf_network
    volumes:
      - "./conf/redis:/etc/redis"
      - "./data/redis:/data:delegated"
    command:
      - "redis-server"
      - "/etc/redis/redis.conf"

  mongo:
    image: mongo:3.2
    ports:
      - "8003:27017"
    expose:
      - 27017
    networks:
      - sf_network
    volumes:
      - "./data/mongodb:/data/db:delegated"

  traefik:
    image: traefik:v1.7
    networks:
      - sf_network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./conf/traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "./conf/traefik/shopping-feed.lan.crt:/etc/traefik/shopping-feed.lan.crt"
      - "./conf/traefik/shopping-feed.lan.key:/etc/traefik/shopping-feed.lan.key"
    command: --api --logLevel=INFO
    expose:
      - 80
      - 443
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"

  mariadb:
    image: mariadb:10.3.10
    networks:
      - sf_network
    volumes:
      - "./conf/mysql:/etc/mysql/conf.d"
      - "./data/mysql:/var/lib/mysql:delegated"
      - "./logs/mysql:/var/log/mysql:delegated"
    ports:
      - "8005:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopping_feed

networks:
  sf_network:
    external: true
