version: "3"
services:
  kibana:
    container_name: sfeed.kibana
    image: docker.elastic.co/kibana/kibana:7.9.2
    networks:
      sf_network:
        ipv4_address: "170.10.5.10"
    expose:
      - 5601
    ports:
      - "8006:5601"
    labels:
      traefik.frontend.rule: "Host:kibana.shopping-feed.lan"
      traefik.backend: "kibana"
      traefik.port: "5601"
      traefik.docker.network: "sf_network"
      traefik.enable: "true"
  elasticsearch:
    container_name: sfeed.elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      sf_network:
        ipv4_address: "170.10.5.11"
    volumes:
      - "./data/elasticsearch:/usr/share/elasticsearch/data:delegated"
    environment:
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "8004:9200"
    labels:
      traefik.frontend.rule: "Host:es.shopping-feed.lan"
      traefik.backend: "elasticsearch"
      traefik.port: "9200"
      traefik.docker.network: "sf_network"
      traefik.enable: "true"
  rabbitmq:
    container_name: sfeed.rabbitmq
    image: rabbitmq:3.7-management-alpine
    networks:
      sf_network:
        ipv4_address: "170.10.5.12"
    volumes:
      - "./data/rabbitmq:/var/lib/rabbitmq:delegated"
    expose:
      - 5672
    ports:
      - "8001:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    labels:
      traefik.frontend.rule: "Host:rbmq.shopping-feed.lan"
      traefik.backend: "rabbitmq"
      traefik.port: "15672"
      traefik.docker.network: "sf_network"
      traefik.enable: "true"
  redis:
    container_name: sfeed.redis
    image: redis:6.0-alpine
    ports:
      - "8002:6379"
    expose:
      - 6379
    networks:
      sf_network:
        ipv4_address: "170.10.5.13"
    volumes:
      - "./conf/redis:/etc/redis"
      - "./data/redis:/data:delegated"
    command:
      - "redis-server"
      - "/etc/redis/redis.conf"
  mongo:
    container_name: sfeed.mongodb
    image: mongo:3.0.2
    ports:
      - "8003:27017"
    expose:
      - 27017
    networks:
      sf_network:
        ipv4_address: "170.10.5.14"
    volumes:
      - "./data/mongodb:/data/db:delegated"
  traefik:
    container_name: sfeed.traefik
    image: traefik:v1.7
    networks:
      sf_network:
        ipv4_address: "170.10.5.15"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./conf/traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "./conf/traefik/shopping-feed.lan.crt:/etc/traefik/shopping-feed.lan.crt"
      - "./conf/traefik/shopping-feed.lan.key:/etc/traefik/shopping-feed.lan.key"
    command: --api --logLevel=INFO
    expose:
      - 80
      - 443
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
  mariadb:
    container_name: sfeed.mariadb
    image: ghcr.io/shoppingflux/mariadb:latest
    networks:
      sf_network:
        ipv4_address: "170.10.5.16"
    volumes:
      - "./conf/mysql:/etc/mysql/conf.d"
      - "./data/mysql:/var/lib/mysql:delegated"
      - "./logs/mysql:/var/log/mysql:delegated"
    ports:
      - "8005:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopping_feed
  s3:
    container_name: sfeed.s3
    image: minio/minio
    command: server /data
    networks:
      sf_network:
        ipv4_address: "170.10.5.17"
    volumes:
      - "./data/s3:/data:delegated"
    ports:
      - "8007:9000"
    expose:
      - 9000
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    labels:
      traefik.frontend.rule: "Host:s3.shopping-feed.lan"
      traefik.backend: "sfeed.s3"
      traefik.port: "9000"
      traefik.docker.network: "sf_network"
      traefik.enable: "true"
networks:
  sf_network:
    external: true
